[package]

name = "error-chain"
version = "0.6.0"
authors = [ "Brian Anderson <banderson@mozilla.com>",
            "Paul Colomiets <paul@colomiets.name>",
            "Colin Kiegel <kiegel@gmx.de>",
            "Yamakaky <yamakaky@yamaworld.fr>"]
description = "Yet another error boilerplate library."

documentation = "https://docs.rs/error-chain"
homepage = "https://github.com/brson/error-chain"
repository = "https://github.com/brson/error-chain"

license = "MIT/Apache-2.0"

[features]
default = ["backtrace", "example_generated", "alloc"]
example_generated = []
alloc = []

[dependencies]
backtrace = { version = "0.3", optional = true }
